<# Render bounded lifecycle evidence as the generated controller digest. #>
[CmdletBinding()]
param([Parameter(Mandatory)][int]$Tracking,[string]$Repo='chase-sets/chase-sets',[switch]$DryRun,[string]$DispatchLog,[string]$CostLedger,[string]$GhCommand='gh',[string]$WaitingOnToddConfig)
$ErrorActionPreference='Stop'
$dispatchPath=if($DispatchLog){$DispatchLog}else{Join-Path $PSScriptRoot 'dispatch-log.jsonl'}
$costPath=if($CostLedger){$CostLedger}else{Join-Path $PSScriptRoot 'cost-ledger.jsonl'}
if(-not(Test-Path -LiteralPath $dispatchPath -PathType Leaf)){throw "no lifecycle log at $dispatchPath"}
# Packaged operator actions are linked, never listed inline (SKILL.md §11, #9228).
$waitingPath=if($WaitingOnToddConfig){$WaitingOnToddConfig}else{Join-Path $PSScriptRoot 'waiting-on-todd.psd1'}
$waitingIssue=if(Test-Path -LiteralPath $waitingPath -PathType Leaf){(Import-PowerShellDataFile -LiteralPath $waitingPath).PinnedIssue}
if($waitingIssue -isnot [int] -or $waitingIssue -lt 1){throw "no pinned Waiting-on-Todd issue in $waitingPath"}
function Read-DigestRows([string]$Path,[int]$Tail){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){return @()};$rows=@();foreach($line in Get-Content -LiteralPath $Path -Tail $Tail){if(-not"$line".Trim()){continue};try{$rows+=($line|ConvertFrom-Json -DateKind String)}catch{throw "malformed lifecycle row in $Path"}};@($rows)}
$rows=Read-DigestRows $dispatchPath 500
if($rows.Count-eq0){throw 'lifecycle log has no rows'}
$latest=@($rows|Sort-Object{[datetimeoffset]::Parse([string]$_.ts)}-Descending|Select-Object -First 1)[0]
$active=@($rows|Where-Object{$_.lane}|Group-Object lane|ForEach-Object{@($_.Group|Sort-Object{[datetimeoffset]::Parse([string]$_.ts)}-Descending|Select-Object -First 1)[0]}|Where-Object{[string]$_.kind-ceq'dispatch'})
$queued=@($rows|Where-Object{$_.pr}|Group-Object pr|ForEach-Object{@($_.Group|Sort-Object{[datetimeoffset]::Parse([string]$_.ts)}-Descending|Select-Object -First 1)[0]}|Where-Object{[string]$_.kind-ceq'enqueue'})
$deploy=@($rows|Where-Object{[string]$_.kind-ceq'deploy-verified'}|Sort-Object{[datetimeoffset]::Parse([string]$_.ts)}-Descending|Select-Object -First 1)
$openBreakers=@($rows|Where-Object{[string]$_.kind-in@('breaker-open','breaker-clear')}|Group-Object{"$($_.issue)/$($_.pr)"}|ForEach-Object{@($_.Group|Sort-Object{[datetimeoffset]::Parse([string]$_.ts)}-Descending|Select-Object -First 1)[0]}|Where-Object{[string]$_.kind-ceq'breaker-open'})
$openDecisions=@($rows|Where-Object{[string]$_.kind-in@('decision-filed','decision-resolved')}|Group-Object issue|ForEach-Object{@($_.Group|Sort-Object{[datetimeoffset]::Parse([string]$_.ts)}-Descending|Select-Object -First 1)[0]}|Where-Object{[string]$_.kind-ceq'decision-filed'})
$today=[datetimeoffset]::UtcNow.ToString('yyyy-MM-dd');$spend=0.0
foreach($row in Read-DigestRows $costPath 5000){if([string]$row.ts -like "$today*"-and$null-ne$row.usd){$spend += [double]$row.usd}}
$stamp=[datetimeoffset]::Parse([string]$latest.ts).ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ss'Z'")
$body=@(
  "**Cycle digest — $stamp**",'', '| | |','|---|---|',
  "| Merge queue | $($queued.Count) lifecycle-confirmed |",
  "| Lanes | $($active.Count) active |",
  "| Real deploy | $(if($deploy.Count){[string]$deploy[0].outcome}else{'unknown'}) |",
  "| Open breakers | $($openBreakers.Count) |",
  ('| Spend today | `${0:N2} |' -f $spend),'',
  "**Open decisions:** $(if($openDecisions.Count){(@($openDecisions|ForEach-Object{"#$($_.issue)"})-join' ')}else{'none.'})",'',
  "**Waiting on Todd:** #$waitingIssue lists every packaged operator action; Todd is assigned to each Now issue.",'',
  '<sub>Generated by `.orchestrator/digest-publish.ps1` from bounded lifecycle and daily cost telemetry.</sub>'
) -join"`n"
if($DryRun){Write-Output $body;return}
$tmp=Join-Path ([IO.Path]::GetTempPath()) ('digest-'+[guid]::NewGuid().ToString('N')+'.md')
try{[IO.File]::WriteAllText($tmp,$body,[Text.UTF8Encoding]::new($false));$out=&$GhCommand issue comment $Tracking --repo $Repo --body-file $tmp 2>&1;if($LASTEXITCODE-ne0){throw "digest post failed: $out"};[ordered]@{ok=$true;tracking=$Tracking;ts=$stamp}|ConvertTo-Json -Compress}finally{Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue}
