<#
.SYNOPSIS
Keep the pinned Waiting-on-Todd issue current from host-packaged `todd-action`
ledger rows (milestone-orchestrator SKILL.md sections 3, 11 and 14; #9228).

The controller ledger is the only membership source. GitHub comments, labels
and prose carry no authority: the host posts as Todd's account, so authorship
cannot distinguish them. Each cycle folds `todd-action` rows by actionId (the
latest ledger line wins), renders the pinned body (Now, Later, Done within the
configured window) and assigns Todd to every issue with a Now action. Only
assignments this script made are ever removed.

Every GitHub mutation is preceded by a durable intent in the state file and is
confirmed by readback before the intent is dropped. Any failed GitHub read
writes nothing that cycle. The body write is a compare-and-swap on the body
alone: it is refused when the body moved between the cycle read and the write.

.EXAMPLE
./waiting-on-todd.ps1            # one cycle against the live pinned issue
./waiting-on-todd.ps1 -DryRun    # render and plan without any write
#>
[CmdletBinding()]
param(
  # Load the shared todd-action/v1 schema, ledger reader and reducers only.
  # log-event.ps1 uses this so the writer and reader share one closed schema.
  [switch]$Library,
  [string]$Config,
  [string]$DispatchLog,
  [string]$StatePath,
  [string]$GhCommand = 'gh',
  # Test seam for the Done window; production uses the current UTC instant.
  [string]$NowUtc,
  [switch]$DryRun
)
$ErrorActionPreference = 'Stop'

$script:ToddActionSchema = 'todd-action/v1'
$script:ToddActionFields = @('ts','kind','toddActionSchema','actionId','issue','state','action','time','unblocks')
$script:ToddActionStates = @('now','later','done')
$script:ToddActionTextLimits = [ordered]@{ action = 400; time = 80; unblocks = 200 }
$script:WaitingOnToddStateSchema = 'waiting-on-todd-state/v1'
$script:WaitingOnToddMarker = '<!-- waiting-on-todd/v1 generated by .orchestrator/waiting-on-todd.ps1 from todd-action ledger rows; edits are overwritten -->'

function Test-ToddActionInteger($Value) {
  return ($Value -is [long] -or $Value -is [int]) -and $Value -ge 1 -and $Value -le [int]::MaxValue
}

# Returns the first invalid field name, or $null for a valid closed row.
function Get-ToddActionRowError($Row) {
  if ($Row -isnot [pscustomobject]) { return 'row' }
  $names = @($Row.PSObject.Properties.Name)
  if ($names.Count -ne $script:ToddActionFields.Count) { return 'fields' }
  foreach ($field in $script:ToddActionFields) { if ($field -cnotin $names) { return $field } }
  $parsed = [datetimeoffset]::MinValue
  if ($Row.ts -isnot [string] -or $Row.ts -cnotmatch '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$' -or
      -not [datetimeoffset]::TryParse($Row.ts, [Globalization.CultureInfo]::InvariantCulture,
        [Globalization.DateTimeStyles]::AssumeUniversal, [ref]$parsed)) { return 'ts' }
  if ($Row.kind -isnot [string] -or $Row.kind -cne 'todd-action') { return 'kind' }
  if ($Row.toddActionSchema -isnot [string] -or $Row.toddActionSchema -cne $script:ToddActionSchema) { return 'toddActionSchema' }
  if ($Row.actionId -isnot [string] -or $Row.actionId -cnotmatch '^[a-z0-9][a-z0-9._-]{0,127}$') { return 'actionId' }
  if (-not (Test-ToddActionInteger $Row.issue)) { return 'issue' }
  if ($Row.state -isnot [string] -or $Row.state -cnotin $script:ToddActionStates) { return 'state' }
  foreach ($field in $script:ToddActionTextLimits.Keys) {
    $value = $Row.$field
    if ($value -isnot [string] -or $value.Length -lt 1 -or $value.Length -gt $script:ToddActionTextLimits[$field] -or
        $value.Trim() -cne $value -or $value -cmatch '\p{Cc}') { return $field }
  }
  return $null
}

function Assert-ToddActionRow($Row) {
  $invalid = Get-ToddActionRowError $Row
  if ($invalid) { throw "TODD_ACTION_INVALID: $invalid" }
}

# Streams the whole ledger: a bounded tail would silently drop older actions.
# Any line naming todd-action must parse; a todd-action row must be closed.
function Read-ToddActionRows([string]$Path, [switch]$AllowMissing) {
  $rows = [Collections.Generic.List[object]]::new()
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
    if ($AllowMissing) { return ,$rows }
    throw "TODD_ACTION_LEDGER_MISSING: $Path"
  }
  $number = 0
  # Shared read so concurrent appends are never blocked; disposed on refusal.
  $reader = [IO.StreamReader]::new([IO.FileStream]::new($Path, [IO.FileMode]::Open, [IO.FileAccess]::Read,
    [IO.FileShare]::ReadWrite -bor [IO.FileShare]::Delete), [Text.UTF8Encoding]::new($false, $true))
  try {
    while ($null -ne ($line = $reader.ReadLine())) {
      $number++
      if (-not $line.Contains('todd-action')) { continue }
      try { $value = $line | ConvertFrom-Json -DateKind String -ErrorAction Stop }
      catch { throw "TODD_ACTION_LEDGER_INVALID: line $number does not parse" }
      if ($value -isnot [pscustomobject] -or $null -eq $value.PSObject.Properties['kind'] -or
          -not ([string]$value.kind).Equals('todd-action', [StringComparison]::OrdinalIgnoreCase)) { continue }
      $invalid = Get-ToddActionRowError $value
      if ($invalid) { throw "TODD_ACTION_LEDGER_INVALID: line $number field $invalid" }
      $rows.Add([pscustomobject]@{ line = $number; value = $value })
    }
  } catch {
    if ($_.Exception.Message -like 'TODD_ACTION_*') { throw }
    throw "TODD_ACTION_LEDGER_INVALID: line $($number + 1) is not readable strict UTF-8"
  } finally { $reader.Dispose() }
  return ,$rows
}

# Latest ledger line per actionId wins. An actionId is bound to one issue for
# life; a rebound id is ambiguous ownership and goes to host triage.
function Get-ToddActionFold([object[]]$Rows) {
  $latest = [Collections.Generic.Dictionary[string,object]]::new([StringComparer]::Ordinal)
  foreach ($row in @($Rows | Sort-Object line)) {
    $value = $row.value
    if ($latest.ContainsKey($value.actionId) -and $latest[$value.actionId].issue -ne $value.issue) {
      throw "TODD_ACTION_ID_CONFLICT: $($value.actionId) is bound to #$($latest[$value.actionId].issue), not #$($value.issue)"
    }
    $latest[$value.actionId] = $value
  }
  return @($latest.Values | Sort-Object @{ Expression = { [long]$_.issue } }, @{ Expression = { $_.actionId } })
}

function ConvertTo-WaitingOnToddCell([string]$Text) { return $Text.Replace('|', '\|') }

function Get-WaitingOnToddBody([object[]]$Actions, [datetimeoffset]$Now, [int]$DoneWindowDays) {
  $cutoff = $Now.AddDays(-$DoneWindowDays)
  $nowRows = @($Actions | Where-Object { $_.state -ceq 'now' })
  $laterRows = @($Actions | Where-Object { $_.state -ceq 'later' })
  $doneRows = @($Actions | Where-Object {
    $_.state -ceq 'done' -and [datetimeoffset]::Parse($_.ts, [Globalization.CultureInfo]::InvariantCulture) -ge $cutoff
  })
  $lines = [Collections.Generic.List[string]]::new()
  $lines.Add($script:WaitingOnToddMarker)
  $lines.Add('This is the one place to see what is waiting on Todd. The controller regenerates it every cycle from its ledger (#9228); edits here are overwritten. Todd is assigned to every issue with a Now action, and assignment is the notification.')
  foreach ($section in @(
      @{ title = 'Now'; rows = $nowRows; intro = 'Human-only actions ready now. Listing an action grants no live execution and waives none of its issue''s window, packet, approval or prerequisite checks.' },
      @{ title = 'Later'; rows = $laterRows; intro = 'Actions whose gates must pass first.' })) {
    $lines.Add('')
    $lines.Add("## $($section.title)")
    $lines.Add('')
    $lines.Add($section.intro)
    $lines.Add('')
    if ($section.rows.Count -eq 0) { $lines.Add('None.'); continue }
    $lines.Add('| Issue | Action | Time | Unblocks |')
    $lines.Add('| --- | --- | --- | --- |')
    foreach ($action in $section.rows) {
      $lines.Add("| #$($action.issue) | $(ConvertTo-WaitingOnToddCell $action.action) | $(ConvertTo-WaitingOnToddCell $action.time) | $(ConvertTo-WaitingOnToddCell $action.unblocks) |")
    }
  }
  $lines.Add('')
  $lines.Add("## Done (last $DoneWindowDays days)")
  $lines.Add('')
  if ($doneRows.Count -eq 0) { $lines.Add('None.') }
  else {
    $lines.Add('| Issue | Action | Done |')
    $lines.Add('| --- | --- | --- |')
    foreach ($action in $doneRows) {
      $lines.Add("| #$($action.issue) | $(ConvertTo-WaitingOnToddCell $action.action) | $($action.ts.Substring(0, 10)) |")
    }
  }
  return ($lines -join "`n")
}

function New-WaitingOnToddState([string]$Repo, [string]$Assignee) {
  return [pscustomobject]@{ schema = $script:WaitingOnToddStateSchema; repo = $Repo; assignee = $Assignee; owned = @(); pending = @() }
}

function Read-WaitingOnToddState([string]$Path, [string]$Repo, [string]$Assignee) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return New-WaitingOnToddState $Repo $Assignee }
  try { $state = [IO.File]::ReadAllText($Path) | ConvertFrom-Json -DateKind String -ErrorAction Stop }
  catch { throw "WAITING_ON_TODD_STATE_INVALID: $Path does not parse" }
  $names = @($state.PSObject.Properties.Name)
  if ($state -isnot [pscustomobject] -or $names.Count -ne 5 -or
      @('schema','repo','assignee','owned','pending' | Where-Object { $_ -cnotin $names }).Count -or
      $state.schema -cne $script:WaitingOnToddStateSchema) { throw 'WAITING_ON_TODD_STATE_INVALID: closed state fields required' }
  if ($state.repo -cne $Repo -or -not ([string]$state.assignee).Equals($Assignee, [StringComparison]::OrdinalIgnoreCase)) {
    throw 'WAITING_ON_TODD_STATE_IDENTITY_MISMATCH: state was written for another repo or assignee'
  }
  foreach ($issue in @($state.owned)) { if (-not (Test-ToddActionInteger $issue)) { throw 'WAITING_ON_TODD_STATE_INVALID: owned issue' } }
  foreach ($intent in @($state.pending)) {
    $intentNames = @($intent.PSObject.Properties.Name)
    $valid = $intent -is [pscustomobject] -and (Test-ToddActionInteger $intent.issue) -and (
      ($intent.op -cin @('add','remove') -and $intentNames.Count -eq 2) -or
      ($intent.op -ceq 'body' -and $intentNames.Count -eq 3 -and $intent.sha256 -cmatch '^[a-f0-9]{64}$'))
    if (-not $valid) { throw 'WAITING_ON_TODD_STATE_INVALID: pending intent' }
  }
  $state.owned = @($state.owned | ForEach-Object { [int]$_ } | Sort-Object -Unique)
  $state.pending = @($state.pending)
  return $state
}

# Pure reconciliation. $Assigned maps every desired, owned and pending issue to
# whether the assignee is currently assigned. A pending add found assigned is
# owned; a pending remove still assigned is retried while undesired. Manual
# assignments are never owned and therefore never removed.
function Get-WaitingOnToddPlan($State, [int[]]$Desired, [hashtable]$Assigned) {
  $owned = [Collections.Generic.SortedSet[int]]::new()
  foreach ($issue in @($State.owned)) { [void]$owned.Add([int]$issue) }
  foreach ($intent in @($State.pending)) {
    $issue = [int]$intent.issue
    if ($intent.op -ceq 'add' -and $Assigned[$issue]) { [void]$owned.Add($issue) }
    if ($intent.op -ceq 'remove' -and -not $Assigned[$issue]) { [void]$owned.Remove($issue) }
  }
  $ops = [Collections.Generic.List[object]]::new()
  foreach ($issue in @($Desired | Sort-Object -Unique)) {
    if (-not $Assigned[[int]$issue]) { $ops.Add([pscustomobject]@{ op = 'add'; issue = [int]$issue }) }
  }
  foreach ($issue in @($owned)) {
    if ($issue -in $Desired) { continue }
    if ($Assigned[$issue]) { $ops.Add([pscustomobject]@{ op = 'remove'; issue = $issue }) }
    else { [void]$owned.Remove($issue) }
  }
  return [pscustomobject]@{ owned = [int[]]@($owned); ops = $ops.ToArray() }
}

if ($Library) { return }

function Read-WaitingOnToddConfig([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "WAITING_ON_TODD_CONFIG_INVALID: missing $Path" }
  $data = Import-PowerShellDataFile -LiteralPath $Path
  $keys = @('Repo','PinnedIssue','Assignee','DoneWindowDays')
  if ($data.Count -ne $keys.Count -or @($keys | Where-Object { -not $data.ContainsKey($_) }).Count -or
      $data.Repo -isnot [string] -or $data.Repo -cnotmatch '^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$' -or
      $data.PinnedIssue -isnot [int] -or $data.PinnedIssue -lt 1 -or
      $data.Assignee -isnot [string] -or $data.Assignee -cnotmatch '^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$' -or
      $data.DoneWindowDays -isnot [int] -or $data.DoneWindowDays -lt 1 -or $data.DoneWindowDays -gt 365) {
    throw 'WAITING_ON_TODD_CONFIG_INVALID: Repo, PinnedIssue, Assignee and DoneWindowDays required'
  }
  return [pscustomobject]$data
}

function Invoke-WaitingOnToddGh([string[]]$Arguments) {
  $global:LASTEXITCODE = 0
  try { $output = @(& $GhCommand @Arguments 2>&1); $code = $LASTEXITCODE }
  catch { return [pscustomobject]@{ ok = $false; text = '' } }
  $stdout = @($output | Where-Object { $_ -isnot [Management.Automation.ErrorRecord] } | ForEach-Object { [string]$_ }) -join "`n"
  return [pscustomobject]@{ ok = ($code -eq 0); text = $stdout }
}

# One issue read. Returns $null on any failure so the caller writes nothing.
function Get-WaitingOnToddIssue([int]$Number) {
  $result = Invoke-WaitingOnToddGh @('api', "repos/$($settings.Repo)/issues/$Number")
  if (-not $result.ok) { return $null }
  try { $issue = $result.text | ConvertFrom-Json -DateKind String -ErrorAction Stop } catch { return $null }
  if ($issue -isnot [pscustomobject] -or -not (Test-ToddActionInteger $issue.number) -or $issue.number -ne $Number -or
      $null -eq $issue.PSObject.Properties['assignees'] -or $null -eq $issue.PSObject.Properties['body'] -or
      ($null -ne $issue.body -and $issue.body -isnot [string])) { return $null }
  $logins = @($issue.assignees | ForEach-Object { if ($_ -is [pscustomobject] -and $_.login -is [string]) { $_.login } else { '' } })
  if ($logins -contains '') { return $null }
  return [pscustomobject]@{
    number = $Number
    body = $issue.body
    assigned = @($logins | Where-Object { $_.Equals($settings.Assignee, [StringComparison]::OrdinalIgnoreCase) }).Count -gt 0
  }
}

function Test-WaitingOnToddSameBody($Left, $Right) {
  if ($null -eq $Left -or $null -eq $Right) { return $null -eq $Left -and $null -eq $Right }
  return $Left -ceq $Right
}

function ConvertTo-WaitingOnToddLf($Text) { if ($null -eq $Text) { return $null }; return ([string]$Text).Replace("`r`n", "`n") }

function Save-WaitingOnToddState($State) {
  $directory = Split-Path -Parent $script:statePathFull
  if (-not (Test-Path -LiteralPath $directory -PathType Container)) { [void](New-Item -ItemType Directory -Path $directory) }
  $json = [ordered]@{ schema = $State.schema; repo = $State.repo; assignee = $State.assignee
    owned = [object[]]@($State.owned); pending = [object[]]@($State.pending) } | ConvertTo-Json -Compress -Depth 4
  $temporary = "$($script:statePathFull).$([guid]::NewGuid().ToString('N')).tmp"
  [IO.File]::WriteAllText($temporary, $json, [Text.UTF8Encoding]::new($false))
  [IO.File]::Move($temporary, $script:statePathFull, $true)
}

$configPath = if ($Config) { $Config } else { Join-Path $PSScriptRoot 'waiting-on-todd.psd1' }
$ledgerPath = if ($DispatchLog) { $DispatchLog } else { Join-Path $PSScriptRoot 'dispatch-log.jsonl' }
$script:statePathFull = [IO.Path]::GetFullPath($(if ($StatePath) { $StatePath } else { Join-Path $PSScriptRoot 'state/waiting-on-todd.json' }))
$settings = Read-WaitingOnToddConfig $configPath
$now = if ($NowUtc) { [datetimeoffset]::Parse($NowUtc, [Globalization.CultureInfo]::InvariantCulture).ToUniversalTime() } else { [datetimeoffset]::UtcNow }

$lock = $null
if (-not $DryRun) {
  $lockDirectory = Split-Path -Parent $script:statePathFull
  if (-not (Test-Path -LiteralPath $lockDirectory -PathType Container)) { [void](New-Item -ItemType Directory -Path $lockDirectory) }
  try {
    $lock = [IO.FileStream]::new("$($script:statePathFull).lock", [IO.FileMode]::OpenOrCreate, [IO.FileAccess]::ReadWrite,
      [IO.FileShare]::None, 1, [IO.FileOptions]::DeleteOnClose)
  } catch { throw "WAITING_ON_TODD_BUSY: another cycle holds the state lock ($($_.Exception.InnerException.Message))" }
}
try {
  $state = Read-WaitingOnToddState $script:statePathFull $settings.Repo $settings.Assignee
  $actions = Get-ToddActionFold (Read-ToddActionRows $ledgerPath)
  $desired = [int[]]@($actions | Where-Object { $_.state -ceq 'now' } | ForEach-Object { [int]$_.issue } | Sort-Object -Unique)
  $body = Get-WaitingOnToddBody $actions $now $settings.DoneWindowDays
  $bodySha = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($body))).ToLowerInvariant()

  # Every read happens before any write. One failed read: nothing is written.
  $pinned = Get-WaitingOnToddIssue $settings.PinnedIssue
  if ($null -eq $pinned) { throw "WAITING_ON_TODD_READ_FAILED: pinned #$($settings.PinnedIssue); nothing written" }
  # Adoption guard: an unseeded ledger never replaces a hand-maintained list.
  if ($actions.Count -eq 0 -and -not ([string]$pinned.body).StartsWith($script:WaitingOnToddMarker, [StringComparison]::Ordinal)) {
    throw "WAITING_ON_TODD_UNSEEDED: pinned #$($settings.PinnedIssue) is hand-written and the ledger has no todd-action rows; seed them first; nothing written"
  }
  $relevant = @(@($desired) + @($state.owned) + @($state.pending | Where-Object { $_.op -cin @('add','remove') } | ForEach-Object { [int]$_.issue }) |
    Where-Object { $null -ne $_ } | Sort-Object -Unique)
  $assigned = @{}
  foreach ($issue in $relevant) {
    $snapshot = Get-WaitingOnToddIssue $issue
    if ($null -eq $snapshot) { throw "WAITING_ON_TODD_READ_FAILED: #$issue; nothing written" }
    $assigned[[int]$issue] = $snapshot.assigned
  }
  $plan = Get-WaitingOnToddPlan $state $desired $assigned
  $bodyCurrent = (ConvertTo-WaitingOnToddLf $pinned.body) -ceq $body
  $summary = [ordered]@{ ok = $true; pinnedIssue = $settings.PinnedIssue; dryRun = [bool]$DryRun
    now = @($actions | Where-Object { $_.state -ceq 'now' }).Count; later = @($actions | Where-Object { $_.state -ceq 'later' }).Count
    desired = [object[]]$desired; owned = [object[]]$plan.owned; adds = [object[]]@(); removes = [object[]]@(); bodyWritten = $false }
  if ($DryRun) {
    $summary.adds = [object[]]@($plan.ops | Where-Object { $_.op -ceq 'add' } | ForEach-Object { $_.issue })
    $summary.removes = [object[]]@($plan.ops | Where-Object { $_.op -ceq 'remove' } | ForEach-Object { $_.issue })
    $summary.bodyCurrent = $bodyCurrent
    $summary.body = $body
    return ($summary | ConvertTo-Json -Compress -Depth 4)
  }

  # Readback-confirmed outcomes from the previous cycle become durable first.
  # A stale body intent carries no ownership and is re-planned below.
  $reconciled = New-WaitingOnToddState $settings.Repo $settings.Assignee
  $reconciled.owned = [int[]]$plan.owned
  if (($state.owned -join ',') -cne ($reconciled.owned -join ',') -or @($state.pending).Count) { Save-WaitingOnToddState $reconciled }
  $state = $reconciled

  foreach ($op in $plan.ops) {
    $state.pending = @([pscustomobject]@{ op = $op.op; issue = $op.issue })
    Save-WaitingOnToddState $state
    $method = if ($op.op -ceq 'add') { 'POST' } else { 'DELETE' }
    $mutation = Invoke-WaitingOnToddGh @('api', '-X', $method, "repos/$($settings.Repo)/issues/$($op.issue)/assignees", '-f', "assignees[]=$($settings.Assignee)")
    if (-not $mutation.ok) { throw "WAITING_ON_TODD_WRITE_FAILED: $($op.op) #$($op.issue); intent kept for the next cycle" }
    $readback = Get-WaitingOnToddIssue $op.issue
    if ($null -eq $readback -or $readback.assigned -ne ($op.op -ceq 'add')) {
      throw "WAITING_ON_TODD_READBACK_UNCONFIRMED: $($op.op) #$($op.issue); intent kept for the next cycle"
    }
    $owned = [Collections.Generic.SortedSet[int]]::new([int[]]@($state.owned))
    if ($op.op -ceq 'add') { [void]$owned.Add($op.issue) } else { [void]$owned.Remove($op.issue) }
    $state.owned = [int[]]@($owned)
    $state.pending = @()
    Save-WaitingOnToddState $state
    if ($op.op -ceq 'add') { $summary.adds += $op.issue } else { $summary.removes += $op.issue }
  }
  $summary.owned = [object[]]$state.owned

  if (-not $bodyCurrent) {
    $state.pending = @([pscustomobject]@{ op = 'body'; issue = $settings.PinnedIssue; sha256 = $bodySha })
    Save-WaitingOnToddState $state
    # Compare-and-swap on the body alone: assignment, label and comment
    # activity never block the write; a moved or deleted body always does.
    $fresh = Get-WaitingOnToddIssue $settings.PinnedIssue
    if ($null -eq $fresh) { throw "WAITING_ON_TODD_READ_FAILED: pinned #$($settings.PinnedIssue) before body write; body not written" }
    if (-not (Test-WaitingOnToddSameBody $fresh.body $pinned.body)) {
      throw "WAITING_ON_TODD_BODY_CAS_MISMATCH: pinned #$($settings.PinnedIssue) body changed during the cycle; body not written"
    }
    $payload = "$($script:statePathFull).$([guid]::NewGuid().ToString('N')).body.json"
    try {
      [IO.File]::WriteAllText($payload, ([ordered]@{ body = $body } | ConvertTo-Json -Compress), [Text.UTF8Encoding]::new($false))
      $mutation = Invoke-WaitingOnToddGh @('api', '-X', 'PATCH', "repos/$($settings.Repo)/issues/$($settings.PinnedIssue)", '--input', $payload)
    } finally { Remove-Item -LiteralPath $payload -Force -ErrorAction SilentlyContinue }
    if (-not $mutation.ok) { throw "WAITING_ON_TODD_WRITE_FAILED: body #$($settings.PinnedIssue); intent kept for the next cycle" }
    $readback = Get-WaitingOnToddIssue $settings.PinnedIssue
    if ($null -eq $readback -or (ConvertTo-WaitingOnToddLf $readback.body) -cne $body) {
      throw "WAITING_ON_TODD_READBACK_UNCONFIRMED: body #$($settings.PinnedIssue); intent kept for the next cycle"
    }
    $state.pending = @()
    Save-WaitingOnToddState $state
    $summary.bodyWritten = $true
  }
  return ($summary | ConvertTo-Json -Compress -Depth 4)
} finally {
  if ($lock) { $lock.Dispose() }
}
